class DomainException(Exception): ...


class ProductsDoesNotExists(DomainException): ...


class OrderAlreadyExists(DomainException): ...


class ConcurrencyException(DomainException): ...


class EventNotSupported(DomainException): ...
