"""rename data to payload

Revision ID: 14e9c833e98e
Revises: 82c4e3fcfeec
Create Date: 2025-12-06 20:05:00.680101

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "14e9c833e98e"
down_revision: Union[str, Sequence[str], None] = "82c4e3fcfeec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "create_order_saga",
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.create_unique_constraint("uq_create_order_saga_id", "create_order_saga", ["id"])
    op.drop_column("create_order_saga", "data")
    op.create_unique_constraint(
        "uq_create_order_saga_step_id", "create_order_saga_step", ["id"]
    )
    op.create_unique_constraint("uq_order_items_id", "order_items", ["id"])
    op.create_unique_constraint("uq_orders_id", "orders", ["id"])
    op.create_unique_constraint("uq_outbox_id", "outbox", ["id"])
    op.create_unique_constraint(
        "uq_processed_messages_id", "processed_messages", ["id"]
    )
    op.create_unique_constraint("uq_products_id", "products", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_products_id", "products", type_="unique")
    op.drop_constraint("uq_processed_messages_id", "processed_messages", type_="unique")
    op.drop_constraint("uq_outbox_id", "outbox", type_="unique")
    op.drop_constraint("uq_orders_id", "orders", type_="unique")
    op.drop_constraint("uq_order_items_id", "order_items", type_="unique")
    op.drop_constraint(
        "uq_create_order_saga_step_id", "create_order_saga_step", type_="unique"
    )
    op.add_column(
        "create_order_saga",
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_create_order_saga_id", "create_order_saga", type_="unique")
    op.drop_column("create_order_saga", "payload")
    # ### end Alembic commands ###
