"""added stocks field for ProductModel

Revision ID: 64ac93fd00da
Revises: fe12d4203e7e
Create Date: 2025-12-13 16:47:52.697395

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '64ac93fd00da'
down_revision: Union[str, Sequence[str], None] = 'fe12d4203e7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stocks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'stocks')
    # ### end Alembic commands ###
