"""added ondelete for OrderItemModel

Revision ID: fe12d4203e7e
Revises: da82d00bb099
Create Date: 2025-12-13 16:20:36.039339

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fe12d4203e7e'
down_revision: Union[str, Sequence[str], None] = 'da82d00bb099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('order_items_order_id_fkey'), 'order_items', type_='foreignkey'
    )
    op.drop_constraint(
        op.f('order_items_product_id_fkey'), 'order_items', type_='foreignkey'
    )
    op.create_foreign_key(
        'fkey_order_items_product_id',
        'order_items',
        'products',
        ['product_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_foreign_key(
        'fkey_order_items_order_id',
        'order_items',
        'orders',
        ['order_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fkey_order_items_product_id', 'order_items', type_='foreignkey')
    op.drop_constraint('fkey_order_items_order_id', 'order_items', type_='foreignkey')
    op.create_foreign_key(
        op.f('order_items_product_id_fkey'),
        'order_items',
        'products',
        ['product_id'],
        ['id'],
    )
    op.create_foreign_key(
        op.f('order_items_order_id_fkey'), 'order_items', 'orders', ['order_id'], ['id']
    )
    # ### end Alembic commands ###
