"""Init

Revision ID: 82c4e3fcfeec
Revises:
Create Date: 2025-12-06 19:57:59.818047

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "82c4e3fcfeec"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column(
            "status",
            sa.Enum(
                "ORDER_CREATED",
                "PAYMENT_PENDING",
                "PAYMENT_COMPLETED",
                "NOTIFICATION_SENT",
                "ANALYTIC_RECORDED",
                "COMPLETED",
                "FAILED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "outbox",
        sa.Column("topic", sa.String(), nullable=False),
        sa.Column("message", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_sent", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "processed_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column("currency", sa.Enum("USD", "EUR", name="currency"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "create_order_saga",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "ORDER_CREATED",
                "PAYMENT_PENDING",
                "PAYMENT_COMPLETED",
                "NOTIFICATION_SENT",
                "ANALYTIC_RECORDED",
                "COMPLETED",
                "FAILED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("current_step_id", sa.UUID(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_create_order_saga_order_id"),
        "create_order_saga",
        ["order_id"],
        unique=False,
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("price", sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column("currency", sa.Enum("USD", "EUR", name="currency"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(op.f("ix_order_items_name"), "order_items", ["name"], unique=False)
    op.create_index(
        op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False
    )
    op.create_table(
        "create_order_saga_step",
        sa.Column("saga_id", sa.UUID(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "ORDER_CREATED",
                "PAYMENT_PENDING",
                "PAYMENT_COMPLETED",
                "NOTIFICATION_SENT",
                "ANALYTIC_RECORDED",
                "COMPLETED",
                "FAILED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "FAILED", name="createorderstepstatus"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["saga_id"],
            ["create_order_saga.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_index(
        op.f("ix_create_order_saga_step_saga_id"),
        "create_order_saga_step",
        ["saga_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_create_order_saga_step_saga_id"), table_name="create_order_saga_step"
    )
    op.drop_table("create_order_saga_step")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_name"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index(op.f("ix_create_order_saga_order_id"), table_name="create_order_saga")
    op.drop_table("create_order_saga")
    op.drop_table("products")
    op.drop_table("processed_messages")
    op.drop_table("outbox")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
