"""added cascade delete for CreateOrderSagaStepModel

Revision ID: da82d00bb099
Revises: ac0a53833dcf
Create Date: 2025-12-13 15:22:21.077000

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'da82d00bb099'
down_revision: Union[str, Sequence[str], None] = 'ac0a53833dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f('create_order_saga_step_saga_id_fkey'),
        'create_order_saga_step',
        type_='foreignkey',
    )
    op.create_foreign_key(
        'fkey_create_order_saga_step_saga_id',
        'create_order_saga_step',
        'create_order_saga',
        ['saga_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fkey_create_order_saga_step_saga_id',
        'create_order_saga_step',
        type_='foreignkey',
    )
    op.create_foreign_key(
        op.f('create_order_saga_step_saga_id_fkey'),
        'create_order_saga_step',
        'create_order_saga',
        ['saga_id'],
        ['id'],
    )
    # ### end Alembic commands ###
