"""Init

Revision ID: db26c3a494ef
Revises:
Create Date: 2025-12-27 17:27:37.083246

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db26c3a494ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'customers',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'order_events',
        sa.Column('order_id', sa.UUID(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column(
            'event_type',
            sa.Enum(
                'ORDER_CREATED',
                'ORDER_INITIALIZED',
                'FAILED_CREATE_ORDER',
                name='eventtypes',
            ),
            nullable=False,
        ),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False
    )
    op.create_table(
        'outbox',
        sa.Column(
            'aggregate_type', sa.Enum('ORDER', name='aggregatetypes'), nullable=False
        ),
        sa.Column('aggregate_id', sa.UUID(), nullable=False),
        sa.Column(
            'event_type',
            sa.Enum(
                'ORDER_CREATED',
                'ORDER_INITIALIZED',
                'FAILED_CREATE_ORDER',
                name='eventtypes',
            ),
            nullable=False,
        ),
        sa.Column('aggregate_version', sa.Integer(), nullable=False),
        sa.Column('topic', sa.String(), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'processed_messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'products',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
        sa.Column('currency', sa.Enum('USD', 'EUR', name='currency'), nullable=False),
        sa.Column('stocks', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'orders',
        sa.Column('customer_id', sa.UUID(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'ORDER_CREATED',
                'ORDER_INITIALIZED',
                'FAILED_CREATE_ORDER',
                name='eventtypes',
            ),
            nullable=False,
        ),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table(
        'create_order_saga',
        sa.Column('order_id', sa.UUID(), nullable=False),
        sa.Column('order_version', sa.Integer(), nullable=False),
        sa.Column(
            'state',
            sa.Enum(
                'STARTED',
                'WAITING_PAYMENT',
                'PAYMENT_COMPLETED',
                'COMPLETED',
                'FAILED',
                name='createordersagastatus',
            ),
            nullable=False,
        ),
        sa.Column('current_step_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['orders.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_create_order_saga_order_id'),
        'create_order_saga',
        ['order_id'],
        unique=False,
    )
    op.create_table(
        'order_items',
        sa.Column('order_id', sa.UUID(), nullable=False),
        sa.Column('product_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=True),
        sa.Column('currency', sa.Enum('USD', 'EUR', name='currency'), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_order_items_name'), 'order_items', ['name'], unique=False)
    op.create_index(
        op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False
    )
    op.create_index(
        op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False
    )
    op.create_table(
        'create_order_saga_step',
        sa.Column('saga_id', sa.UUID(), nullable=False),
        sa.Column(
            'event_type',
            sa.Enum(
                'ORDER_CREATED',
                'ORDER_INITIALIZED',
                'FAILED_CREATE_ORDER',
                name='eventtypes',
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                'SUCCESS',
                'IN_PROGRESS',
                'COMPENSATED',
                'FAILED',
                name='createorderstepstatus',
            ),
            nullable=False,
        ),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['saga_id'], ['create_order_saga.id'], ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_create_order_saga_step_saga_id'),
        'create_order_saga_step',
        ['saga_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_create_order_saga_step_saga_id'), table_name='create_order_saga_step'
    )
    op.drop_table('create_order_saga_step')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_name'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_create_order_saga_order_id'), table_name='create_order_saga')
    op.drop_table('create_order_saga')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('products')
    op.drop_table('processed_messages')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    op.drop_table('customers')
    # ### end Alembic commands ###
