"""added product id to OrderItemModel

Revision ID: ac0a53833dcf
Revises: 1b88dea1af6a
Create Date: 2025-12-06 20:36:32.197654

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ac0a53833dcf'
down_revision: Union[str, Sequence[str], None] = '1b88dea1af6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### use_cases auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_id', sa.UUID(), nullable=False))
    op.create_index(
        op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False
    )
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'])
    # ### end Alembic use_cases ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### use_cases auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_column('order_items', 'product_id')
    # ### end Alembic use_cases ###
