"""updated ordereventtypes

Revision ID: 9a821a6ee62c
Revises: 2415ac80e1e5
Create Date: 2026-01-31 03:18:46.966639

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9a821a6ee62c'
down_revision: Union[str, Sequence[str], None] = '2415ac80e1e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        ALTER TYPE ordereventtypes
        ADD VALUE IF NOT EXISTS 'CHARGED_PAYMENT'
    """)
    op.execute("""
        ALTER TYPE ordereventtypes
        ADD VALUE IF NOT EXISTS 'PRODUCTS_RESERVED'
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
