"""updated OutboxModel

Revision ID: 297db31ddcb9
Revises: d3aa0a427bf6
Create Date: 2026-01-02 18:51:19.792818

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '297db31ddcb9'
down_revision: Union[str, Sequence[str], None] = 'd3aa0a427bf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'order_events',
        'payload',
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
    )
    op.add_column('outbox', sa.Column('action', sa.String(), nullable=False))
    op.add_column(
        'outbox',
        sa.Column('external_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.drop_column('outbox', 'name')
    op.drop_column('outbox', 'aggregate_id')
    op.drop_column('outbox', 'aggregate_type')
    op.drop_column('outbox', 'type')
    op.drop_column('outbox', 'aggregate_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'outbox', sa.Column('aggregate_version', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        'outbox',
        sa.Column(
            'type',
            postgresql.ENUM('EVENT', 'COMMAND', name='messagetype'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'outbox',
        sa.Column(
            'aggregate_type',
            postgresql.ENUM('ORDER', name='aggregatetypes'),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        'outbox', sa.Column('aggregate_id', sa.UUID(), autoincrement=False, nullable=False)
    )
    op.add_column('outbox', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('outbox', 'external_reference')
    op.drop_column('outbox', 'action')
    op.alter_column(
        'order_events',
        'payload',
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
