"""Init

Revision ID: 48eea09f1904
Revises:
Create Date: 2026-02-28 13:58:19.729334

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48eea09f1904'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'order_events',
        sa.Column('order_id', sa.UUID(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column(
            'event_type',
            sa.Enum(
                'ORDER_CREATED',
                'ORDER_INITIALIZED',
                'PRODUCTS_RESERVED',
                'PRODUCTS_COMMITTED',
                'PAYMENT_CHARGED',
                'NOTIFIED_CUSTOMER_SUCCESS_ORDER_CREATED',
                'FAILED_CREATE_ORDER',
                name='ordereventtypes',
            ),
            nullable=False,
        ),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_order_events_order_id'), 'order_events', ['order_id'], unique=False)
    op.create_table(
        'orders',
        sa.Column('customer_id', sa.Uuid(), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'ORDER_CREATED',
                'ORDER_INITIALIZED',
                'PRODUCTS_RESERVED',
                'PRODUCTS_COMMITTED',
                'PAYMENT_CHARGED',
                'NOTIFIED_CUSTOMER_SUCCESS_ORDER_CREATED',
                'FAILED_CREATE_ORDER',
                name='ordereventtypes',
            ),
            nullable=False,
        ),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_table(
        'outbox',
        sa.Column('action', sa.String(), nullable=False),
        sa.Column('topic', sa.String(), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('external_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('producer', sa.String(), nullable=False),
        sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'processed_messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'create_order_saga',
        sa.Column('order_id', sa.UUID(), nullable=False),
        sa.Column('order_version', sa.Integer(), nullable=False),
        sa.Column(
            'state',
            sa.Enum(
                'STARTED',
                'WAITING_PAYMENT',
                'PAYMENT_COMPLETED',
                'WAITING_PRODUCTS_COMMITTED',
                'WAITING_NOTIFY_ORDER_COMPLETED',
                'COMPLETED',
                'FAILED',
                name='createordersagastatus',
            ),
            nullable=False,
        ),
        sa.Column('current_step_id', sa.UUID(), nullable=False),
        sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['orders.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_create_order_saga_order_id'), 'create_order_saga', ['order_id'], unique=False
    )
    op.create_table(
        'create_order_saga_step',
        sa.Column('saga_id', sa.UUID(), nullable=False),
        sa.Column(
            'event_type',
            sa.Enum(
                'ORDER_CREATED',
                'ORDER_INITIALIZED',
                'PRODUCTS_RESERVED',
                'PRODUCTS_COMMITTED',
                'PAYMENT_CHARGED',
                'NOTIFIED_CUSTOMER_SUCCESS_ORDER_CREATED',
                'FAILED_CREATE_ORDER',
                name='ordereventtypes',
            ),
            nullable=False,
        ),
        sa.Column(
            'status',
            sa.Enum(
                'SUCCESS', 'IN_PROGRESS', 'COMPENSATED', 'FAILED', name='createorderstepstatus'
            ),
            nullable=False,
        ),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['saga_id'], ['create_order_saga.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_create_order_saga_step_saga_id'),
        'create_order_saga_step',
        ['saga_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_create_order_saga_step_saga_id'), table_name='create_order_saga_step')
    op.drop_table('create_order_saga_step')
    op.drop_index(op.f('ix_create_order_saga_order_id'), table_name='create_order_saga')
    op.drop_table('create_order_saga')
    op.drop_table('processed_messages')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_order_events_order_id'), table_name='order_events')
    op.drop_table('order_events')
    # ### end Alembic commands ###
